#!/bin/zsh -eu

# Photos that have been copied from a camera or downloaded from the web
# often have awkward file names or spurius xattrs. Fix all that.

# brew install imagemagick ghostscript
# brew tap homebrew-ffmpeg/ffmpeg
# brew install homebrew-ffmpeg/ffmpeg/ffmpeg --with-webp

if [[ "$1" == "" ]]
then
  echo "Usage: $0 root_dir [root_dir2 ...]"
  exit 1
fi

ROOT_DIR=$( dirname "$0" )

for PHOTO_ROOT in "$@"
do
  echo
  echo "Searching for dotfiles in ${PHOTO_ROOT} ..."
  find "${PHOTO_ROOT}" -name .DS_Store -print0 | xargs -0 rm
  find "${PHOTO_ROOT}" -name ".*"

  echo
  echo "Removing extended attributes from ${PHOTO_ROOT} ..."
  find "${PHOTO_ROOT}" -print0 | xargs -0 xattr -c

  echo
  echo "Searching for filenames with non-standard characters in ${PHOTO_ROOT} ..."
  find "${PHOTO_ROOT}" | egrep "[^A-Za-z0-9./_-]" || true

  echo
  echo "Fixing permissions on files/dirs in ${PHOTO_ROOT} ..."
  # chown -R root:wheel "${PHOTO_ROOT}"
  find "${PHOTO_ROOT}" -type f -print0 | xargs -0 chmod 444
  find "${PHOTO_ROOT}" -type d -print0 | xargs -0 chmod 555

  echo
  echo "Searching for corrupt images in ${PHOTO_ROOT} ..."
  "${ROOT_DIR}"/clean_photos_fast.py "${PHOTO_ROOT}"
done
