#!/bin/zsh -eu

# Photos that have been copied from a camera or downloaded from the web
# often have awkward file names or spurius xattrs. Clean all of those
# issues up.

if [[ "$1" == "" ]]
then
  echo "Usage: $0 root_dir [root_dir2 ...]"
  exit 1
fi

HELPER="${0}_helper"

for PHOTOROOT in $*
do
  echo
  echo "Searching for dotfiles in ${PHOTOROOT} ..."
  find ${PHOTOROOT} -name .DS_Store -exec rm "{}" \;
  find ${PHOTOROOT} -name ".*"

  echo
  echo "Removing extended attributes from ${PHOTOROOT} ..."
  # Is much faster to use: ls -ablR@ | egrep "@"
  find ${PHOTOROOT} -exec ${HELPER} "{}" \;

  echo
  echo "Searching for filenames with non-standard characters in ${PHOTOROOT} ..."
  find ${PHOTOROOT} | egrep "[^A-Za-z0-9./_-]" || true

  echo
  echo "Fixing permissions on files/dirs in ${PHOTOROOT} ..."
  # chown -R root:wheel ${PHOTOROOT}
  find ${PHOTOROOT} -type f -exec chmod 644 "{}" \;
  # find ${PHOTOROOT} -type d -exec chmod 555 "{}" \;

  echo
  echo "Searching for corrupt images in ${PHOTOROOT} ..."
  for f in $( find ${PHOTOROOT} -type f ) ; do
	identify ${f} 1>&-  # brew install imagemagick ffmpeg
  done
done
