#!/bin/zsh

# golang version
GOVER=$( go version | awk '{ print $3 }' | sed 's/go//1' )

[[ ! -f go.mod ]] && exit

# Verify the go.mod file is valid
go mod tidy -go="${GOVER}" -compat="${GOVER}"

# If that changed go.mod, check it in
git diff --quiet go.mod || (git add go.mod && git commit -m 'go mod tidy' && git push)

[[ ! -f go.sum ]] && exit

# Update all of the modules
go get -u ./...

go mod tidy -go="${GOVER}" -compat="${GOVER}"

# If no changes, exit
git diff --quiet go.mod go.sum && exit

# Verify the new modules (if any) work
make test

# Make the changes permanent
(git add go.mod go.sum && git commit -m 'Update to latest modules' && git push) || true
