#!/bin/bash -eu

# During handling, copying, editing, etc. the access and modification dates
# on photos will get updated. When uploading a photo to Google Photos it
# uses one of these dates as the "picture taken" date. If the photo is a
# scan of a picture taken many years ago this can leave the date wildly
# inaccurate.
#
# Assume that the containing directory is of the form YYYYMMDD_ccccc. From
# The name of the directory, extract the day the photo was taken. Use that
# date to set the access and modified dates on the file.

function usage() {
  echo "$@"
  echo
  echo "Usage: $( basename $0 ) dirName [[dirName2] ... ]"
  echo
  echo "Where dirName is of the form: /foo/bar/bas/YYYYMMDD.*"
  exit 1
}

[ $# -ge 1 ] || usage 'Wrong number of arguments.'

while [[ $# -ge 1 ]] ; do
  DATED_DIR=$1

  DATE=$( basename "${DATED_DIR}" )
  DATE=${DATE:0:8}
  echo ${DATE} | egrep "^\d{8}$" > /dev/null || usage "Could not extract date from ${DATED_DIR}. Found ${DATE}."

  ROOT=$( dirname $0 )

  $ROOT/setAccModDate $DATE "${DATED_DIR}"

  shift
done
