#!/bin/zsh -eu

# Photos saved from Telegram have an awkward naming.
# Simplify that.

for OLD_NAME in "$@"
do
  NEW_NAME=$( echo "${OLD_NAME}" | sed 's/photo_//g' | sed 's/-//g' | sed 's/ /_/g' )
  mv "${OLD_NAME}" "${NEW_NAME}"
done