#!/bin/zsh -eu

# Photos saved from Telegram have an awkward naming. Simplify that.
#  photo_2026-08-26 08.31.11.jpeg  ->  20260826_08.31.11.jpeg

for OLD_NAME in "$@"
do
  NEW_NAME=$( echo "${OLD_NAME}" | sed 's/photo_//g' | sed 's/-//g' | sed 's/ /_/g' )
  mv "${OLD_NAME}" "${NEW_NAME}"
done