#!/bin/zsh -eu

#
# Update all the things.
#

# Chrome
open -a "Google Chrome" chrome://settings/help

# MacOS software
softwareupdate --all --install --force

# Brew
brew doctor
brew update
brew upgrade

for repo in $( find ~ -name ".git" -type d -prune ) ; do
  R=$( dirname $repo )
  echo
  echo $R
  echo
  cd $R

  # Ignore repositories that do not have a remote.
  REMOTE=$( git remote -v )
  if [[ "${REMOTE}" != "" ]] ; then
    git pull
  fi

  # Update any Golang modules.
  if [[ -f go.mod ]] ; then
    ~/bin/macos/golang-modup
    make test
  fi

  # Display any modified files.
  git status

  cd
  echo
done
