#!/bin/zsh -eu

#
# Update files in the given git repos, including go modules
# Give it the path to the repo or to the .git directory in the repo
#

# Update all of the go.mod files in this tree
updateGoModules () {
  ~/bin/macos/golang-modup
  find . -name 'go.mod' -type f -prune -exec ~/bin/macos/golang-modup {} \;
}

# Update a single git repo
updateRepo () {
  REPO=$1

  echo
  echo
  print -P "%F{green}${REPO}%f"
  echo

  cd "${REPO}"

  # Only pull if there is a remote
  [[ "$( git remote -v )" != "" ]] && git pull

  # Update golang modules
  updateGoModules
}

for GIT_REPO in "$@"
do
  # Remove trailing "/.git" if present
  GIT_REPO=${GIT_REPO/%\/.git/}
  updateRepo "${GIT_REPO}"
done
