#!/bin/zsh -eu

ROOT=$( dirname "$0" )

#
# Update/sync all the software and source on this Mac
#

# Update/sync installed Mac software
updateSoftware () {
  # MacOS software
  echo "Updating MacOS software (requires privileges)"
  sudo softwareupdate --all --install --force --verbose --restart
  sudo --remove-timestamp  # Delete cached credentials

  # Update/sync apps
  open -a "Google Chrome" chrome://settings/help
  open -a Battle.net.app
  open -a JetBrains\ Toolbox.app
  open -a messages
  open -a notes
  open -a zoom.us
}

# Update everything that brew manages
updateBrew () {
  brew doctor
  brew cleanup
  brew update
  brew upgrade
  brew cleanup
  brew doctor
}

# Update all of the git repos in the user's tree
updateRepos () {
  find ~ -name '.git' -type d -prune -exec "${ROOT}/update-repo" {} \;
}

updateSoftware
updateBrew
updateRepos
